config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'download', to: 'comparator#download'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "comparator#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comparator_controller.rb
require_relative '../../lib/tools/alg.rb'

class ComparatorController < ApplicationController

  before_action :authenticate_user!

  def index
    @email = current_user.email

  end

  def download

    send_file '/home/kirill/hello/public/comparator_tar (1)/Kirpich/lib/tools/excel.xls', :disposition => 'attachment'
  end
end
threads = []

threads << Thread.new { Parse_akc.new }
threads << Thread.new { Parse_auto_sto.new }
threads << Thread.new { Parse_autoliga.new }

threads.each { |thr| thr.join }

par1, par2, par3 = threads[0].value, threads[1].value, threads[2].value

comp = Comprator.new(par1, par3, par2)
comp.compare_services

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comparator_helper.rb
module ComparatorHelper
end

app/views/comparator/index.html.erb
<h1><%= @email %></h1>
<%= button_to 'download', download_path, method: :get, class: :btn %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Comparator" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Comparator</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
<!--            <li><%#= link_to "Link3", "/path3"  %></li>-->
          </ul>
          <%= link_to 'logout', destroy_user_session_path, method: :delete, style: 'float:right;', class: 'navbar-text' %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>